my_string = input('Введите несколько слов, через пробел: ')
quantity = len(my_string)
print('Количество введённых символов:', quantity)
print('Верхний регистр:', my_string .upper())
print('Нижний регистр:', my_string .lower())
my_string0 = my_string.replace(" ", "")
print('Без пробелов:', my_string0)
print(my_string[0])
print(my_string[-1])